apiVersion : v1
kind : Service
metadata:
  name: posts-srv
spec:
  type : NodePort
  selector :
    app: posts
  ports : 
    - name : posts
      protocol : TCP
      port : 4000 # node external port so if the machine have request on port 8080 which calls node external port 4000 which will call the target port
      targetPort : 4000 #nodejs app port working on so if nodejs listens 4000 then target port is 4000 etc