apiVersion: skaffold/v2alpha3
kind : Config
deploy:
  kubectl:
    manifests :
      - ./infra/k8s/**
build:
  local:
    push: false
  artifacts:
    - image: zyadashraf/client
      context: client
      docker:
        dockerfile : Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest : .
    - image: zyadashraf/blog_posts
      context: posts
      docker:
        dockerfile : Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest : .
    - image: zyadashraf/blog_comments
      context: comments
      docker:
        dockerfile : Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest : .
    - image: zyadashraf/blog_query
      context: query
      docker:
        dockerfile : Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest : .
    - image: zyadashraf/blog_moderation
      context: moderation
      docker:
        dockerfile : Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest : .
    - image: zyadashraf/blog_event-bus
      context: event-bus
      docker:
        dockerfile : Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest : .