apiVersion: v1
kind: Service
metadata:
  name : comments-clusterip-srv
spec:
  type : ClusterIP #Kubernets Maks it ClusterIP by default if i didnt provide it
  selector :
    app : comments
  ports : 
    - name : comments
      protocol : TCP
      port : 4001
      targetPort : 4001
  