apiVersion: v1
kind: Service
metadata:
  name : moderation-clusterip-srv
spec:
  type : ClusterIP #Kubernets Maks it ClusterIP by default if i didnt provide it
  selector :
    app : moderation
  ports : 
    - name : moderation
      protocol : TCP
      port : 4003
      targetPort : 4003
  