apiVersion: v1
kind: Service
metadata:
  name : query-clusterip-srv
spec:
  type : ClusterIP #Kubernets Maks it ClusterIP by default if i didnt provide it
  selector :
    app : query
  ports : 
    - name : query
      protocol : TCP
      port : 4002
      targetPort : 4002
  